# Generated by Django 5.1.6 on 2025-02-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_diagnosis_date_patient_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='condition',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergens',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_diagnoses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_treatments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='recent_diagnosis',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
