# Generated by Django 5.1.6 on 2025-02-25 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_condition_patient_allergens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='past_diagnoses',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='past_treatments',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='recent_diagnosis',
        ),
        migrations.AddField(
            model_name='patient',
            name='condition',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
